import type { IcmsCalculatorFormInput } from './types';

export interface IcmsExample {
  id: string;
  title: string;
  subtitle: string;
  values: IcmsCalculatorFormInput;
}

export const ICMS_EXAMPLES: IcmsExample[] = [
  {
    id: 'icms-simples',
    title: 'ICMS simples',
    subtitle: 'Venda com frete e alíquota de origem',
    values: {
      tipoCalculo: 'icms_proprio',
      valorProduto: '1.000,00',
      frete: '100,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '',
      aliquotaIpi: '',
      ufOrigem: 'SP',
      ufDestino: 'MG',
      aliquotaOrigem: '12',
      aliquotaInternaDestino: '',
      mva: '',
      reducaoBase: '',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'icms-st',
    title: 'ICMS-ST',
    subtitle: 'Produto com IPI manual e MVA',
    values: {
      tipoCalculo: 'icms_st',
      valorProduto: '35.231,64',
      frete: '0,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '3.435,08',
      aliquotaIpi: '',
      ufOrigem: 'DF',
      ufDestino: 'MG',
      aliquotaOrigem: '4',
      aliquotaInternaDestino: '18',
      mva: '63,90',
      reducaoBase: '0',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'icms-st-frete',
    title: 'ICMS-ST com frete',
    subtitle: 'Operação completa com frete e desconto',
    values: {
      tipoCalculo: 'icms_e_icms_st',
      valorProduto: '5.000,00',
      frete: '300,00',
      seguro: '0,00',
      outrasDespesas: '50,00',
      desconto: '100,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '250,00',
      aliquotaIpi: '',
      ufOrigem: 'GO',
      ufDestino: 'SP',
      aliquotaOrigem: '12',
      aliquotaInternaDestino: '18',
      mva: '40',
      reducaoBase: '0',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'ipi',
    title: 'IPI',
    subtitle: 'IPI por alíquota sobre o produto',
    values: {
      tipoCalculo: 'ipi',
      valorProduto: '1.000,00',
      frete: '50,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '',
      aliquotaIpi: '5',
      ufOrigem: '',
      ufDestino: '',
      aliquotaOrigem: '',
      aliquotaInternaDestino: '',
      mva: '',
      reducaoBase: '',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'pis-cofins',
    title: 'PIS/COFINS',
    subtitle: 'Base comum com alíquotas federais',
    values: {
      tipoCalculo: 'pis_cofins',
      valorProduto: '2.000,00',
      frete: '150,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '',
      aliquotaIpi: '',
      ufOrigem: '',
      ufDestino: '',
      aliquotaOrigem: '',
      aliquotaInternaDestino: '',
      mva: '',
      reducaoBase: '',
      aliquotaPis: '1,65',
      aliquotaCofins: '7,60',
      creditoPis: '0,00',
      creditoCofins: '0,00',
      aliquotaFcp: '',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'difal-fcp',
    title: 'DIFAL + FCP',
    subtitle: 'Operação interestadual com fundo de combate à pobreza',
    values: {
      tipoCalculo: 'difal',
      valorProduto: '1.500,00',
      frete: '100,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '',
      aliquotaIpi: '',
      ufOrigem: 'SP',
      ufDestino: 'RJ',
      aliquotaOrigem: '12',
      aliquotaInternaDestino: '18',
      mva: '',
      reducaoBase: '0',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '2',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'fcp',
    title: 'FCP',
    subtitle: 'Fundo calculado sobre a base da operação',
    values: {
      tipoCalculo: 'fcp',
      valorProduto: '1.200,00',
      frete: '0,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '',
      aliquotaIpi: '',
      ufOrigem: '',
      ufDestino: '',
      aliquotaOrigem: '',
      aliquotaInternaDestino: '',
      mva: '',
      reducaoBase: '',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '2',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
  {
    id: 'ibs-cbs',
    title: 'IBS/CBS',
    subtitle: 'Simulação da reforma tributária',
    values: {
      tipoCalculo: 'ibs_cbs',
      valorProduto: '3.000,00',
      frete: '120,00',
      seguro: '0,00',
      outrasDespesas: '0,00',
      desconto: '0,00',
      valorIcmsInformado: '',
      aliquotaIcms: '',
      valorIpiManual: '',
      aliquotaIpi: '',
      ufOrigem: '',
      ufDestino: '',
      aliquotaOrigem: '',
      aliquotaInternaDestino: '',
      mva: '',
      reducaoBase: '',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '',
      aliquotaIbs: '8',
      aliquotaCbs: '9',
      creditoIbs: '0,00',
      creditoCbs: '0,00',
    },
  },
  {
    id: 'icms-reverso-70',
    title: 'ICMS reverso com redução de 70%',
    subtitle: 'Parte do ICMS final para recuperar a base original',
    values: {
      tipoCalculo: 'icms_reverso',
      valorProduto: '8.254,40',
      frete: '',
      seguro: '',
      outrasDespesas: '',
      desconto: '',
      valorIcmsInformado: '297,16',
      aliquotaIcms: '12',
      valorIpiManual: '',
      aliquotaIpi: '',
      ufOrigem: '',
      ufDestino: '',
      aliquotaOrigem: '',
      aliquotaInternaDestino: '',
      mva: '',
      reducaoBase: '70',
      aliquotaPis: '',
      aliquotaCofins: '',
      creditoPis: '',
      creditoCofins: '',
      aliquotaFcp: '',
      aliquotaIbs: '',
      aliquotaCbs: '',
      creditoIbs: '',
      creditoCbs: '',
    },
  },
];
